### ISSUE TITLE
1.7.10 Extra Utilities and Ex Compressum

### ISSUE THREAD

**Issue by Dom063** [portablejim/VeinMiner#53]
I added in the compressed stone hammer from Ex Compressum under hammer and compressed cobblestone from Extra Utilities, but vein mining on the block does not work. Does veinminer not support those mods? I have the config for override all block and all tools configured on as well.

**Comment by portablejim** [comment]
Fixed. Otherwise see #89

**Comment by PeteGeorgopoulos** [comment]
Just had this issue. For those who are still having issues. this is the correct name to use:
excompressum:compressedHammerStone . Just change the last bit for the hammer material
